this version works perfectly. Major change is added googleApiReadyService through $q.
which fixed this:

TypeError: Cannot read property 'load' of undefined

on this line:
    init: function() {
      googleApiClient = gapi.client.load('drive', 'v2');  <===
    },

somehow the routing caused that, as there was no such error before routing was added.

Other items:

- why the post-auth was necessary before, but not now (with the routing added?). because of that, the auth button is now moved into index.html

- the duplicated list items issue likely was caused post-auth as well?

- why
        $scope.$apply(function() {
        });
  was necessary earlier, but now it's causing error with routing adde, error related to $digest
        https://docs.angularjs.org/error/$rootScope/inprog?p0=$digest

TODO:
- still need to add error handling, such as:
  Error: [$sanitize:badparse] http://errors.angularjs.org/1.4.8/$sanitize/badparse?p0=%3CJul%2028%2C%2020…%3E%20%3Cat%20weblogic.work.ExecuteThread.run(ExecuteThread.java%3A181)%3E